package net.sf.ddg.hibernate;

// default package
// Generated 19-feb-2008 16.59.34 by Hibernate Tools 3.2.0.b9

/**
 * DatiUltSett generated by hbm2java
 */
public class DatiUltSett implements java.io.Serializable {

	private int id;
	private String nomeProgetto;
	private int pr;
	private Double pagineAccedute;
	private Integer pagineWeb;
	private Double fileScaricati;
	private Integer etaUltRelease;
	private Integer ultimoAccAdmin;
	private Integer commitCvs;
	private Integer bugAperti;
	private Integer bugPendenti;
	private Integer bugTotali;
	private Integer patchAperte;
	private Integer patchPendenti;
	private Integer patchTotali;
	private Integer patchChiuse;
	private Integer releaseTotali;
	private Integer openFeatureRequest;
	private Integer pendingFeatureRequest;
	private Integer totalFeatureRequest;

	public DatiUltSett() {
	}

	public DatiUltSett(int id, String nomeProgetto, int pr) {
		this.id = id;
		this.nomeProgetto = nomeProgetto;
		this.pr = pr;
	}

	public DatiUltSett(int id, String nomeProgetto, int pr,
			Double pagineAccedute, Integer pagineWeb, Double fileScaricati,
			Integer etaUltRelease, Integer ultimoAccAdmin, Integer commitCvs,
			Integer bugAperti, Integer bugPendenti, Integer bugTotali,
			Integer patchAperte, Integer patchPendenti, Integer patchTotali,
			Integer patchChiuse, Integer releaseTotali,
			Integer openFeatureRequest, Integer pendingFeatureRequest,
			Integer totalFeatureRequest) {
		this.id = id;
		this.nomeProgetto = nomeProgetto;
		this.pr = pr;
		this.pagineAccedute = pagineAccedute;
		this.pagineWeb = pagineWeb;
		this.fileScaricati = fileScaricati;
		this.etaUltRelease = etaUltRelease;
		this.ultimoAccAdmin = ultimoAccAdmin;
		this.commitCvs = commitCvs;
		this.bugAperti = bugAperti;
		this.bugPendenti = bugPendenti;
		this.bugTotali = bugTotali;
		this.patchAperte = patchAperte;
		this.patchPendenti = patchPendenti;
		this.patchTotali = patchTotali;
		this.patchChiuse = patchChiuse;
		this.releaseTotali = releaseTotali;
		this.openFeatureRequest = openFeatureRequest;
		this.pendingFeatureRequest = pendingFeatureRequest;
		this.totalFeatureRequest = totalFeatureRequest;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNomeProgetto() {
		return this.nomeProgetto;
	}

	public void setNomeProgetto(String nomeProgetto) {
		this.nomeProgetto = nomeProgetto;
	}

	public int getPr() {
		return this.pr;
	}

	public void setPr(int pr) {
		this.pr = pr;
	}

	public Double getPagineAccedute() {
		return this.pagineAccedute;
	}

	public void setPagineAccedute(Double pagineAccedute) {
		this.pagineAccedute = pagineAccedute;
	}

	public Integer getPagineWeb() {
		return this.pagineWeb;
	}

	public void setPagineWeb(Integer pagineWeb) {
		this.pagineWeb = pagineWeb;
	}

	public Double getFileScaricati() {
		return this.fileScaricati;
	}

	public void setFileScaricati(Double fileScaricati) {
		this.fileScaricati = fileScaricati;
	}

	public Integer getEtaUltRelease() {
		return this.etaUltRelease;
	}

	public void setEtaUltRelease(Integer etaUltRelease) {
		this.etaUltRelease = etaUltRelease;
	}

	public Integer getUltimoAccAdmin() {
		return this.ultimoAccAdmin;
	}

	public void setUltimoAccAdmin(Integer ultimoAccAdmin) {
		this.ultimoAccAdmin = ultimoAccAdmin;
	}

	public Integer getCommitCvs() {
		return this.commitCvs;
	}

	public void setCommitCvs(Integer commitCvs) {
		this.commitCvs = commitCvs;
	}

	public Integer getBugAperti() {
		return this.bugAperti;
	}

	public void setBugAperti(Integer bugAperti) {
		this.bugAperti = bugAperti;
	}

	public Integer getBugPendenti() {
		return this.bugPendenti;
	}

	public void setBugPendenti(Integer bugPendenti) {
		this.bugPendenti = bugPendenti;
	}

	public Integer getBugTotali() {
		return this.bugTotali;
	}

	public void setBugTotali(Integer bugTotali) {
		this.bugTotali = bugTotali;
	}

	public Integer getPatchAperte() {
		return this.patchAperte;
	}

	public void setPatchAperte(Integer patchAperte) {
		this.patchAperte = patchAperte;
	}

	public Integer getPatchPendenti() {
		return this.patchPendenti;
	}

	public void setPatchPendenti(Integer patchPendenti) {
		this.patchPendenti = patchPendenti;
	}

	public Integer getPatchTotali() {
		return this.patchTotali;
	}

	public void setPatchTotali(Integer patchTotali) {
		this.patchTotali = patchTotali;
	}

	public Integer getPatchChiuse() {
		return this.patchChiuse;
	}

	public void setPatchChiuse(Integer patchChiuse) {
		this.patchChiuse = patchChiuse;
	}

	public Integer getReleaseTotali() {
		return this.releaseTotali;
	}

	public void setReleaseTotali(Integer releaseTotali) {
		this.releaseTotali = releaseTotali;
	}

	public Integer getOpenFeatureRequest() {
		return this.openFeatureRequest;
	}

	public void setOpenFeatureRequest(Integer openFeatureRequest) {
		this.openFeatureRequest = openFeatureRequest;
	}

	public Integer getPendingFeatureRequest() {
		return this.pendingFeatureRequest;
	}

	public void setPendingFeatureRequest(Integer pendingFeatureRequest) {
		this.pendingFeatureRequest = pendingFeatureRequest;
	}

	public Integer getTotalFeatureRequest() {
		return this.totalFeatureRequest;
	}

	public void setTotalFeatureRequest(Integer totalFeatureRequest) {
		this.totalFeatureRequest = totalFeatureRequest;
	}

}
